# Autogenerated wrapper script for Icestorm_jll for aarch64-linux-musl-cxx11
export icebox_asc2hlc, icebox_chipdb, icebox_colbuf, icebox_diff, icebox_explain, icebox_hlc2asc, icebox_html, icebox_maps, icebox_stat, icebox_vlog, icebram, icemulti, icepack, icepll, icetime, iceunpack

JLLWrappers.@generate_wrapper_header("Icestorm")
JLLWrappers.@declare_executable_product(icebox_asc2hlc)
JLLWrappers.@declare_executable_product(icebox_chipdb)
JLLWrappers.@declare_executable_product(icebox_colbuf)
JLLWrappers.@declare_executable_product(icebox_diff)
JLLWrappers.@declare_executable_product(icebox_explain)
JLLWrappers.@declare_executable_product(icebox_hlc2asc)
JLLWrappers.@declare_executable_product(icebox_html)
JLLWrappers.@declare_executable_product(icebox_maps)
JLLWrappers.@declare_executable_product(icebox_stat)
JLLWrappers.@declare_executable_product(icebox_vlog)
JLLWrappers.@declare_executable_product(icebram)
JLLWrappers.@declare_executable_product(icemulti)
JLLWrappers.@declare_executable_product(icepack)
JLLWrappers.@declare_executable_product(icepll)
JLLWrappers.@declare_executable_product(icetime)
JLLWrappers.@declare_executable_product(iceunpack)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        icebox_asc2hlc,
        "bin/icebox_asc2hlc",
    )

    JLLWrappers.@init_executable_product(
        icebox_chipdb,
        "bin/icebox_chipdb",
    )

    JLLWrappers.@init_executable_product(
        icebox_colbuf,
        "bin/icebox_colbuf",
    )

    JLLWrappers.@init_executable_product(
        icebox_diff,
        "bin/icebox_diff",
    )

    JLLWrappers.@init_executable_product(
        icebox_explain,
        "bin/icebox_explain",
    )

    JLLWrappers.@init_executable_product(
        icebox_hlc2asc,
        "bin/icebox_hlc2asc",
    )

    JLLWrappers.@init_executable_product(
        icebox_html,
        "bin/icebox_html",
    )

    JLLWrappers.@init_executable_product(
        icebox_maps,
        "bin/icebox_maps",
    )

    JLLWrappers.@init_executable_product(
        icebox_stat,
        "bin/icebox_stat",
    )

    JLLWrappers.@init_executable_product(
        icebox_vlog,
        "bin/icebox_vlog",
    )

    JLLWrappers.@init_executable_product(
        icebram,
        "bin/icebram",
    )

    JLLWrappers.@init_executable_product(
        icemulti,
        "bin/icemulti",
    )

    JLLWrappers.@init_executable_product(
        icepack,
        "bin/icepack",
    )

    JLLWrappers.@init_executable_product(
        icepll,
        "bin/icepll",
    )

    JLLWrappers.@init_executable_product(
        icetime,
        "bin/icetime",
    )

    JLLWrappers.@init_executable_product(
        iceunpack,
        "bin/iceunpack",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
